# snRNA e snoRNA

## O que são ribonucleoproteínas?

São complexos formados por ácidos ribonucléicos e RBPs ou proteínas de ligação a RNA, 
alguns exemplos são os ribossomos e os snRNPs, estes últimos formados pela associação de snRNAs a proteínas, preenchendo funções de extrema relevância para o processo de splicing.

## Descrições desses dois ncRNAs

### snRNAs

São pequenos RNAs sintetizados no núcleo, especificamente nos corpos de Cajal, possuem um comprimento médio de 150nt e podem ser transcritos tanto pela RNAPol-II quanto pela RNAPol-III. Preenchem funções relevantes no processo de splicing. Se tem conhecimento de por volta de 10 snRNAs e estes são divididos em duas classes:

  * Os Sm, transcritos pela RNAPol-II, são exportados para o citoplasma, onde sofrem clivagem na extremidade 3' resultando na formação de um loop. A estrutura em loop 3' é necessária para o reconhecimento pela proteína SMN, que proporcionará a hipermetilação de seu cap 5', originando um cap de tri-metilguanosina, que é necessário para seu endereçamento celular para os corpúsculos de Cajal, onde podem passar por pseudouridinilações e mais metilações.
  
  * Os Lsm, transcritos pela RNAPol-III, possuindo um cap 5' de monometilfosfato, nunca deixam o núcleo, se ligando a proteína La, o que proporciona a ligação do anel Lsm, o que indica seu endereçamento para o nucléolo, onde por fim pode passar pelas pseudouridinilações e metilações que o farão funcional.

### snoRNAs

São pequenos RNAs localizados no nucléolo, podendo se maturar nele mesmo ou nos corpúsculos de Cajal. Tem tamanho variando de 60 a 170nt. São, em sua grande parte, transcritos
pela RNAPol-II. Se dividem, também, em duas classes, diferenciando-se pelos boxes, ou sequências curtas conservadas, que possuem:

  * Os box H/ACA possuem duas estruturas secundárias interceptadas por um box H e um box ACA.
  
  * Os box C/D possuem pareamentos nas suas extremidades, onde são localizados os dois boxes, C e D.
  
## Onde eles atuam?

### snRNAs

A grande maioria participa do spliceossomo (Abaixo descreve-se splicing U2):
  
  * Inicialmente, há a ligação do complexo U1 ao sítio de splicing 5', mediada pela complementaridade do snRNA que possui. 
  * Logo em seguida, ocorre a ligação do complexo U2 ao ponto de ramificação do íntron. 
  
  * As reações de transestefiricação subsequentes, propiciadas inicialmente pela hidroxila 2 do ponto de ramificação, irão resultar na ligação dos éxons adjacentes e a liberação do íntron na forma de laço.

### snoRNAs

Formam os complexos de snoRNPs, com as porções ribonucleotídicas agindo como um "guia", indicando seções nos rRNAs não processados e, com o pareamento destes, proporcionam reações de metilação e pseudouridinilação, estas necessárias para a clivagem e formação da estrutura final do ribossomo. 
  
## A quais doenças estão relacionados?

### snRNAs

* **Atrofia muscular espinhal**: Mutações no SMN que podem resultar na perda da função das suas proteínas, com sua responsabilidade na síntese dos snRNAs Sm sendo prejudicada.

* **Medulloblastoma**: Alguns desses tumores possuem um U1 snRNA mutado, o que leva a alterações negativas no splicing.

### snoRNAs

* **Síndrome de Prader-Willi**: Foi observado que perdas de cópias do SNORD116 está associado ao surgimento dessa síndrome [@Sahoo_2008].

* **Autismo**: Ganho de cópias do SNORD115 pode estar associado ao surgimento de algumas formas de autismo [@Bolton_2004]
